apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sblockcreationwithdefaultserviceaccount
spec:
  crd:
    spec:
      names:
        kind: K8sBlockCreationWithDefaultServiceAccount
      validation:
        legacySchema: false
  targets:
  - rego: |
      package k8sblockcreationwithdefaultserviceaccount

      violation[{"msg": msg}] {
        input.review.operation == "CREATE"
        username := object.get(input.review.userInfo, "username", "")
        startswith(username, "system:serviceaccount:")
        endswith(username, ":default")
        msg := "Creation is blocked with default service account."
      }
    target: admission.k8s.gatekeeper.sh
